# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitiCli < Formula
  desc "个人命令行工具集"
  homepage "https://github.com/SeSiTing/homebrew-siti-cli"
  version "2.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.12/siti-cli_2.0.12_darwin_amd64.tar.gz"
      sha256 "d5ab4cd2c1dbb5a40ef7c7f6c5a0205fd8cea7a417e50f1a7090eb618209cb05"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.12/siti-cli_2.0.12_darwin_arm64.tar.gz"
      sha256 "347466358757e55d199e9a2f57dabb45872732feb073ba2a47b89346a8f10a05"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.12/siti-cli_2.0.12_linux_amd64.tar.gz"
      sha256 "a1179d85058ad498bf85abdd5241500a8675c361f71d45eb84200cf2c4efed77"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.12/siti-cli_2.0.12_linux_arm64.tar.gz"
      sha256 "7b856cc8f74c2687d50f0bf8fb5b02b3f96b145d8d4c9be6105d796e939a512f"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  def caveats
    <<~EOS
      首次安装后运行以下命令配置 shell wrapper：
        echo 'eval "$(siti init zsh)"' >> ~/.zshrc
        source ~/.zshrc
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siti --version")
  end
end
