# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitiCli < Formula
  desc "个人命令行工具集"
  homepage "https://github.com/SeSiTing/homebrew-siti-cli"
  version "2.0.40"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.40/siti-cli_2.0.40_darwin_amd64.tar.gz"
      sha256 "832fd5a5c36e26224548818cc572e597e4b3ae2b27d6b93fd8b118bed67b85b9"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.40/siti-cli_2.0.40_darwin_arm64.tar.gz"
      sha256 "107fc345c6fb01c60db6f2ccb4a59f0c5de53409812e50246e5aaa119d0c2ee3"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.40/siti-cli_2.0.40_linux_amd64.tar.gz"
      sha256 "1fc9db317e4b6c11dd4b4a7f3f2ef4bcd59b1e8ea46e7e4fd6560935ee5f7a15"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.40/siti-cli_2.0.40_linux_arm64.tar.gz"
      sha256 "5a0e57f53b2b87b93739b2a9ac166431a5420ebc921e7393b52edf21cf514881"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  def caveats
    <<~EOS
      首次安装后运行以下命令配置 shell wrapper：
        siti init zsh --auto
        source ~/.zshrc
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siti --version")
  end
end
