# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitiCli < Formula
  desc "个人命令行工具集"
  homepage "https://github.com/SeSiTing/homebrew-siti-cli"
  version "2.0.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.27/siti-cli_2.0.27_darwin_amd64.tar.gz"
      sha256 "5cce625ddb2df7a7308cd3cbf881ca3b501b990989b270cb68bbfe403fd9e1da"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.27/siti-cli_2.0.27_darwin_arm64.tar.gz"
      sha256 "abbd2bc8d6b861f61f7ff15776dbec3f20104a7710a440979c528a6e6e518ed9"

      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.27/siti-cli_2.0.27_linux_amd64.tar.gz"
      sha256 "e916a8fadb425021d2644c6e53c9eece3f4b4f72eaf134d58a29f471bf25ec04"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SeSiTing/siti-cli/releases/download/v2.0.27/siti-cli_2.0.27_linux_arm64.tar.gz"
      sha256 "80cd01491faaa1f0df6c00012fabe85769cfc1ea2f3723d8289bc87b86fd6b97"
      define_method(:install) do
        bin.install "siti"
        zsh_completion.install "completions/_siti" => "_siti"
        bash_completion.install "completions/siti.bash" => "siti"
      end
    end
  end

  def caveats
    <<~EOS
      首次安装后运行以下命令配置 shell wrapper：
        siti init zsh --auto
        source ~/.zshrc
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siti --version")
  end
end
